function matcam(action);

global rootdir
global S V A
global Stot Vtot Atot
global beta0 beta1
global tetatot tetatotrad lambda_plot lambda
global alfa roc_plot roc gamma
global force_spring force_load
global force_acc force_tot
global force_x force_y rpm
global RRtotgamma VVtotgamma AAtotgamma
global Rtotrad 
global rof
global extload extloadtot
global betaload betaloadtot
global betaload0 betaload1
global x_pitch y_pitch
global x_pitch_plot y_pitch_plot
global x_contour y_contour
global x_contour_plot y_contour_plot
global x_rolfol y_rolfol
global x_rod y_rod x_rod_ref y_rod_ref
global x_center y_center
global x_pressangle y_pressangle
global x_refangle y_refangle
global x_boreleft x_boreright y_bore
global currentloadfile currentliftfile
global bcr
global rof
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% if no argument -> specifying 'initialise'

if nargin<1,
	action='initialise';
end;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% create controls

if strcmp(action,'initialise'),
	set(figure,'position',[5 32.5 1017.5 695]),
	set(gcf,'name','matcam cam design  (PMA-K.U.Leuven)'),
	set(axes,'position',[.07 .10 .57 .7]);
	axis('off');
   
   rootdir=cd;

   extloadtot=zeros(361,1);
	Stot=zeros(361,1);
	Vtot=zeros(361,1);
	Atot=zeros(361,1);


	frame1=uicontrol(gcf,...
		'style','frame',...
		'position',[505 475 510 215],...
		'backgroundcolor',[.45 .45 .45]);

	frame2=uicontrol(gcf,...
		'style','frame',...
		'position',[505 180 510 290],...
		'backgroundcolor',[.45 .45 .45]);

	frame3=uicontrol(gcf,...
		'style','frame',...
		'position',[505 60 510 115],...
		'backgroundcolor',[.45 .45 .45]);

%------------------------------------------------------------------------------------------------
% FRAME1
	
	f1p=get(frame1,'position').*[1 1 0 0]+[5 5 0 0];

	for i=(1:8),
		f1pk1(i,:)=f1p+[0 25*(i-1) 125 25];
		f1pk2(i,:)=f1p+[125 25*(i-1) 125 25];
		f1pk3(i,:)=f1p+[250 25*(i-1) 125 25];
		f1pk4(i,:)=f1p+[375 25*(i-1) 125 25];
	end

	genmotlaw_tekst=uicontrol(gcf,...
		'visible','on',...
		'style','text',...
		'string','generate motion law',...
		'HorizontalAlignment','center',...
		'foregroundcolor',[.25 .25 1],...
		'backgroundcolor',[.85 .85 .85],...
		'position',f1pk1(8,:)+[0 5 375 0]);

	rb_genmotlaw(1)=uicontrol(gcf,...
		'style','radio',...
		'string','harmonic',...
		'position',f1pk1(7,:)+[0 5 0 -5],...
		'value',1);

	rb_genmotlaw(2)=uicontrol(gcf,...
		'style','radio',...
		'string','cycloidal',...
		'position',f1pk2(7,:)+[0 5 0 -5],...
		'value',0);

	popup_genmotlaw=uicontrol(gcf,...
		'style','popup',...
		'string','1|2|3|4|5|6',...
		'position',f1pk3(7,:)+[0 5 -5 -5]);

	rb_genmotlaw(3)=uicontrol(gcf,...
		'style','radio',...
		'string','polynomial',...
		'position',f1pk4(7,:)+[0 5 0 -5],...
		'value',0);

	genmotlaw_startangle_tekst=uicontrol(gcf,...
		'visible','on',...
		'style','text',...
		'string','start angle (degrees):',...
		'HorizontalAlignment','left',...
		'position',f1pk1(6,:));

	genmotlaw_startangle_edit=uicontrol(gcf,...
		'visible','on',...
		'style','edit',...
		'string','',...
		'HorizontalAlignment','left',...
		'backgroundcolor',[.65 .65 .65],...
		'position',f1pk2(6,:));

	genmotlaw_startlift_tekst=uicontrol(gcf,...
		'visible','on',...
		'style','text',...
		'HorizontalAlignment','left',...
		'string','lift (mm):',...
		'position',f1pk1(5,:));

	genmotlaw_startlift_edit=uicontrol(gcf,...
		'visible','on',...
		'style','edit',...
		'HorizontalAlignment','left',...
		'string','',...
		'backgroundcolor',[.65 .65 .65],...
		'position',f1pk2(5,:));

	genmotlaw_startvel_tekst=uicontrol(gcf,...
		'visible','on',...
		'style','text',...
		'string','velocity (mm/degr):',...
		'HorizontalAlignment','left',...
		'position',f1pk1(4,:));

	genmotlaw_startacc_tekst=uicontrol(gcf,...
		'visible','on',...
		'style','text',...
		'string','acceleration (mm/degr^2):',...
		'HorizontalAlignment','left',...
		'position',f1pk1(3,:));

	genmotlaw_startjerk_tekst=uicontrol(gcf,...
		'visible','on',...
		'style','text',...
		'string','jerk (mm/degr^3):',...
		'HorizontalAlignment','left',...
		'position',f1pk1(2,:));

	genmotlaw_endangle_tekst=uicontrol(gcf,...
		'visible','on',...
		'style','text',...
		'string','end angle (degrees):',...
		'HorizontalAlignment','left',...
		'position',f1pk3(6,:));

	genmotlaw_endangle_edit=uicontrol(gcf,...
		'visible','on',...
		'style','edit',...
		'string','',...
		'HorizontalAlignment','left',...
		'backgroundcolor',[.65 .65 .65],...
		'position',f1pk4(6,:));

	genmotlaw_endlift_tekst=uicontrol(gcf,...
		'visible','on',...
		'style','text',...
		'string','lift (mm):',...
		'HorizontalAlignment','left',...
		'position',f1pk3(5,:));

	genmotlaw_endlift_edit=uicontrol(gcf,...
		'visible','on',...
		'style','edit',...
		'string','',...
		'HorizontalAlignment','left',...
		'backgroundcolor',[.65 .65 .65],...
		'position',f1pk4(5,:));

	genmotlaw_endvel_tekst=uicontrol(gcf,...
		'visible','on',...
		'style','text',...
		'string','velocity (mm/degr):',...
		'HorizontalAlignment','left',...
		'position',f1pk3(4,:));

	genmotlaw_endacc_tekst=uicontrol(gcf,...
		'visible','on',...
		'style','text',...
		'string','acceleration (mm/degr^2):',...
		'HorizontalAlignment','left',...
		'position',f1pk3(3,:));

	genmotlaw_endjerk_tekst=uicontrol(gcf,...
		'visible','on',...
		'style','text',...
		'string','jerk (mm/degr^3):',...
		'HorizontalAlignment','left',...
		'position',f1pk3(2,:));

			genmotlaw_startvel_edit=uicontrol(gcf,...
					'visible','on',...
					'style','edit',...
					'HorizontalAlignment','left',...
					'string','',...
					'backgroundcolor',[.55 .55 .55],...
					'position',f1pk2(4,:));...
			genmotlaw_startacc_edit=uicontrol(gcf,...
					'visible','on',...
					'style','edit',...
					'HorizontalAlignment','left',...
					'string','',...
					'backgroundcolor',[.55 .55 .55],...
					'position',f1pk2(3,:));...
			genmotlaw_startjerk_edit=uicontrol(gcf,...
					'visible','on',...
					'style','edit',...
					'HorizontalAlignment','left',...
					'string','',...
					'backgroundcolor',[.55 .55 .55],...
					'position',f1pk2(2,:));...
			genmotlaw_endvel_edit=uicontrol(gcf,...
					'visible','on',...
					'style','edit',...
					'HorizontalAlignment','left',...
					'string','',...
					'backgroundcolor',[.55 .55 .55],...
					'position',f1pk4(4,:));...
			genmotlaw_endacc_edit=uicontrol(gcf,...
					'visible','on',...
					'style','edit',...
					'HorizontalAlignment','left',...
					'string','',...
					'backgroundcolor',[.55 .55 .55],...
					'position',f1pk4(3,:));...
			genmotlaw_endjerk_edit=uicontrol(gcf,...
					'visible','on',...
					'style','edit',...
					'HorizontalAlignment','left',...
					'string','',...
					'backgroundcolor',[.55 .55 .55],...
					'position',f1pk4(2,:));...

	genmotlaw_calc=uicontrol(gcf,...
		'visible','on',...
		'style','push',...
		'string','start calculation',...
		'HorizontalAlignment','left',...
		'position',f1pk1(1,:),...
		'callback','matcam(''genmotlawcalc'')');

	genmotlaw_add=uicontrol(gcf,...
		'visible','on',...
		'style','push',...
		'string','add',...
		'HorizontalAlignment','left',...
      'position',f1pk2(1,:)+[0 0 -62.5 0],... 
      'callback','matcam(''genmotlawadd'')');

	genmotlaw_clear=uicontrol(gcf,...
		'visible','on',...
		'style','push',...
		'string','clear all',...
		'HorizontalAlignment','left',...
		'position',f1pk2(1,:)+[62.5 0 -62.5 0],...
		'backgroundcolor',[.75 .55 .55],...
		'callback','matcam(''genmotlawclear'')');
   
   genmotlaw_save=uicontrol(gcf,...
		'visible','on',...
		'style','push',...
		'string','save file',...
		'HorizontalAlignment','left',...
		'position',f1pk3(1,:)+[0 0 -62.5 0],...
		'callback','matcam(''genmotlawsave'')');
   
   genmotlaw_load=uicontrol(gcf,...
		'visible','on',...
		'style','push',...
		'string','load file',...
		'HorizontalAlignment','left',...
		'position',f1pk3(1,:)+[62.5 0 -62.5 0],...
		'callback','matcam(''genmotlawload'')');
   
   genmotlaw_current=uicontrol(gcf,...
		'visible','on',...
		'style','text',...
		'string','current file:',...
		'HorizontalAlignment','left',...
		'backgroundcolor',[.65 .65 .65],...
		'position',f1pk4(1,:)+[0 0 -70 0]);

%------------------------------------------------------------------------------------------------
% FRAME2
	f2p=get(frame2,'position').*[1 1 0 0]+[5 5 0 0];

	for i=(1:11),
		f2pk1(i,:)=f2p+[0 25*(i-1) 125 25];
		f2pk2(i,:)=f2p+[125 25*(i-1) 125 25];
		f2pk3(i,:)=f2p+[250 25*(i-1) 125 25];
		f2pk4(i,:)=f2p+[375 25*(i-1) 125 25];
	end

	analmotlaw_tekst=uicontrol(gcf,...
		'visible','on',...
		'style','text',...
		'string','analyse general motion law',...
		'backgroundcolor',[.85 .85 .85],...
		'foregroundcolor',[.25 .25 1],...
		'HorizontalAlignment','center',...
		'position',f2pk1(11,:)+[0 5 375 0]);

	kin_tekst=uicontrol(gcf,...
		'visible','on',...
		'style','text',...
		'string','kinematics input',...
		'HorizontalAlignment','center',...
		'position',f2pk1(10,:)+[0 0 122.5 0]);

	dyn_tekst=uicontrol(gcf,...
		'visible','on',...
		'style','text',...
		'string','dynamics input',...
		'HorizontalAlignment','center',...
		'position',f2pk3(10,:)+[2.5 0 122.5 0]);

	bcr_tekst=uicontrol(gcf,...
		'visible','on',...
		'style','text',...
		'string','base radius (mm):',...
		'HorizontalAlignment','left',...
		'position',f2pk1(9,:));

	bcr_edit=uicontrol(gcf,...
		'visible','on',...
		'style','edit',...
		'string','',...
		'backgroundcolor',[.65 .65 .65],...
		'HorizontalAlignment','left',...
		'position',f2pk2(9,:)+[0 0 -2.5 0]);

	rof_tekst=uicontrol(gcf,...
		'visible','on',...
		'style','text',...
		'string','follower radius (mm):',...
		'HorizontalAlignment','left',...
		'position',f2pk1(8,:));

	rof_edit=uicontrol(gcf,...
		'visible','on',...
		'style','edit',...
		'string','',...
		'backgroundcolor',[.65 .65 .65],...
		'HorizontalAlignment','left',...
		'position',f2pk2(8,:)+[0 0 -2.5 0]);

	exc_tekst=uicontrol(gcf,...
		'visible','on',...
		'style','text',...
		'string','excentricity (mm):',...
		'HorizontalAlignment','left',...
		'position',f2pk1(7,:));

	exc_edit=uicontrol(gcf,...
		'visible','on',...
		'style','edit',...
		'string','',...
		'backgroundcolor',[.65 .65 .65],...
		'HorizontalAlignment','left',...
		'position',f2pk2(7,:)+[0 0 -2.5 0]);
%
	contourgrad_tekst=uicontrol(gcf,...
		'visible','on',...
		'style','text',...
		'string','cam position (grad):',...
		'HorizontalAlignment','left',...
		'position',f2pk1(6,:)+[0 5 0 -5]);

	contourgrad_edit=uicontrol(gcf,...
		'visible','on',...
		'style','edit',...
		'string','',...
		'backgroundcolor',[.65 .65 .65],...
		'HorizontalAlignment','left',...
		'position',f2pk2(6,:)+[0 5 -2.5 -5]);
 %  
   mass_tekst=uicontrol(gcf,...
		'visible','on',...
		'style','text',...
		'string','equivalent mass (kg):',...
		'HorizontalAlignment','left',...
		'position',f2pk3(9,:)+[2.5 0 0 0]);

	mass_edit=uicontrol(gcf,...
		'visible','on',...
		'style','edit',...
		'string','',...
		'backgroundcolor',[.65 .65 .65],...
		'HorizontalAlignment','left',...
		'position',f2pk4(9,:)+[2.5 0 -2.5 0]);

	spring_tekst=uicontrol(gcf,...
		'visible','on',...
		'style','text',...
		'string','spring constant (N/mm):',...
		'HorizontalAlignment','left',...
		'position',f2pk3(8,:)+[2.5 0 0 0]);

	spring_edit=uicontrol(gcf,...
		'visible','on',...
		'style','edit',...
		'string','',...
		'backgroundcolor',[.65 .65 .65],...
		'HorizontalAlignment','left',...
		'position',f2pk4(8,:)+[2.5 0 -2.5 0]);

	sprload_tekst=uicontrol(gcf,...
		'visible','on',...
		'style','text',...
		'string','spring preload (N):',...
		'HorizontalAlignment','left',...
		'position',f2pk3(7,:)+[2.5 0 0 0]);

	sprload_edit=uicontrol(gcf,...
		'visible','on',...
		'style','edit',...
		'string','',...
		'backgroundcolor',[.65 .65 .65],...
		'HorizontalAlignment','left',...
		'position',f2pk4(7,:)+[2.5 0 -2.5 0]);

	rpm_tekst=uicontrol(gcf,...
		'visible','on',...
		'style','text',...
		'string','cam rpm:',...
		'HorizontalAlignment','left',...
		'position',f2pk3(6,:)+[2.5 5 0 -5]);

	rpm_edit=uicontrol(gcf,...
		'visible','on',...
		'style','edit',...
		'string','',...
		'backgroundcolor',[.65 .65 .65],...
		'HorizontalAlignment','left',...
		'position',f2pk4(6,:)+[2.5 5 -2.5 -5]);

	rb_analmotlaw(1)=uicontrol(gcf,...
		'style','radio',...
		'string','lift',...
		'position',f2pk1(5,:)+[0 0 125 0],...
		'value',1);

	rb_analmotlaw(2)=uicontrol(gcf,...
		'style','radio',...
		'string','velocity',...
		'position',f2pk1(4,:)+[0 0 125 0],...
		'value',0);

	rb_analmotlaw(3)=uicontrol(gcf,...
		'style','radio',...
		'string','acceleration',...
		'position',f2pk1(3,:)+[0 0 125 0],...
		'value',0);

	rb_analmotlaw(4)=uicontrol(gcf,...
		'style','radio',...
		'string','pressure angle',...
		'position',f2pk1(2,:)+[0 0 125 0],...
		'value',0);

	rb_analmotlaw(5)=uicontrol(gcf,...
		'style','radio',...
		'string','radius of curvature',...
		'position',f2pk3(5,:)+[0 0 125 0],...
		'value',0);

	rb_analmotlaw(6)=uicontrol(gcf,...
		'style','radio',...
		'string','contact force',...
		'position',f2pk3(3,:)+[0 0 125 0],...
		'value',0);

	rb_analmotlaw(7)=uicontrol(gcf,...
		'style','radio',...
		'string','cam contour',...
		'position',f2pk3(4,:)+[0 0 125 0],...
		'value',0);
      
   rb_analmotlaw(8)=uicontrol(gcf,...
		'style','radio',...
		'string','X-Y reaction forces',...
		'position',f2pk3(2,:)+[0 0 125 0],...
		'value',0);

	plot_start=uicontrol(gcf,...
		'style','push',...
		'string','start plotting',...
		'position',f2pk3(1,:)+[0 0 125 0],...
		'callback','matcam(''plot'')');

	calc_start=uicontrol(gcf,...
		'style','push',...
		'string','start calculations',...
		'position',f2pk1(1,:)+[0 0 125 0],...
		'callback','matcam(''calc'')');

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% FRAME3
	
	f3p=get(frame3,'position').*[1 1 0 0]+[5 5 0 0];

	for i=(1:4),
		f3pk1(i,:)=f3p+[0 25*(i-1) 125 25];
		f3pk2(i,:)=f3p+[125 25*(i-1) 125 25];
		f3pk3(i,:)=f3p+[250 25*(i-1) 125 25];
		f3pk4(i,:)=f3p+[375 25*(i-1) 125 25];
	end

	genextload_tekst=uicontrol(gcf,...
		'visible','on',...
		'style','text',...
		'string','generate external load (linear)',...
		'HorizontalAlignment','center',...
		'foregroundcolor',[.25 .25 1],...
		'backgroundcolor',[.85 .85 .85],...
		'position',f3pk1(4,:)+[0 5 375 0]);

	genextload_startangle_tekst=uicontrol(gcf,...
		'visible','on',...
		'style','text',...
		'string','start angle (degrees):',...
		'HorizontalAlignment','left',...
		'position',f3pk1(3,:));

	genextload_startangle_edit=uicontrol(gcf,...
		'visible','on',...
		'style','edit',...
		'string','',...
		'HorizontalAlignment','left',...
		'backgroundcolor',[.65 .65 .65],...
		'position',f3pk2(3,:));

	genextload_startload_tekst=uicontrol(gcf,...
		'visible','on',...
		'style','text',...
		'HorizontalAlignment','left',...
		'string','load (N):',...
		'position',f3pk1(2,:));

	genextload_startload_edit=uicontrol(gcf,...
		'visible','on',...
		'style','edit',...
		'HorizontalAlignment','left',...
		'string','',...
		'backgroundcolor',[.65 .65 .65],...
		'position',f3pk2(2,:));

	genextload_endangle_tekst=uicontrol(gcf,...
		'visible','on',...
		'style','text',...
		'string','end angle (degrees):',...
		'HorizontalAlignment','left',...
		'position',f3pk3(3,:));

	genextload_endangle_edit=uicontrol(gcf,...
		'visible','on',...
		'style','edit',...
		'string','',...
		'HorizontalAlignment','left',...
		'backgroundcolor',[.65 .65 .65],...
		'position',f3pk4(3,:));

	genextload_endload_tekst=uicontrol(gcf,...
		'visible','on',...
		'style','text',...
		'string','load (N):',...
		'HorizontalAlignment','left',...
		'position',f3pk3(2,:));

	genextload_endload_edit=uicontrol(gcf,...
		'visible','on',...
		'style','edit',...
		'string','',...
		'HorizontalAlignment','left',...
		'backgroundcolor',[.65 .65 .65],...
		'position',f3pk4(2,:));

  	genextload_calc=uicontrol(gcf,...
		'visible','on',...
		'style','push',...
		'string','start calculation',...
		'HorizontalAlignment','left',...
		'position',f3pk1(1,:),... %+[0 0 75 0],...
		'callback','matcam(''genextloadcalc'')');

	genextload_add=uicontrol(gcf,...
		'visible','on',...
		'style','push',...
		'string','add',...
		'HorizontalAlignment','left',...
		'position',f3pk2(1,:)+[0 0 -62.5 0],... %+[75 0 -25 0],...
		'callback','matcam(''genextloadadd'')');

	genextload_clear=uicontrol(gcf,...
		'visible','on',...
		'style','push',...
		'string','clear all',...
		'HorizontalAlignment','left',...
		'position',f3pk2(1,:)+[62.5 0 -62.5 0],... %+[50 0 75 0],...
		'backgroundcolor',[.75 .55 .55],...
		'callback','matcam(''genextloadclear'')');
   
   genextload_save=uicontrol(gcf,...
		'visible','on',...
		'style','push',...
		'string','save file',...
		'HorizontalAlignment','left',...
		'position',f3pk3(1,:)+[0 0 -62.5 0],...
		'callback','matcam(''genextloadsave'')');
   
   genextload_load=uicontrol(gcf,...
		'visible','on',...
		'style','push',...
		'string','load file',...
		'HorizontalAlignment','left',...
		'position',f3pk3(1,:)+[62.5 0 -62.5 0],...
		'callback','matcam(''genextloadload'')');
   
   genextload_current=uicontrol(gcf,...
		'visible','on',...
		'style','text',...
		'string','current file:',...
		'HorizontalAlignment','left',...
		'backgroundcolor',[.65 .65 .65],...
		'position',f3pk4(1,:)+[0 0 -70 0]);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% make radio buttons mutually exclusive

for i=(1:3),
	set(rb_genmotlaw(i),'userdata',rb_genmotlaw(:,[1:(i-1),(i+1):3]))
end

call=[
	'mutex_genmotlaw=get(gcf,''currentobject'');',...
	'if(get(mutex_genmotlaw,''value'')==1),',...
		'set(get(mutex_genmotlaw,''userdata''),''value'',0),',...
	'else,',...
		'set(mutex_genmotlaw,''value'',1),',...
	'end'];...

set(rb_genmotlaw,'callback',call);

%---------------------------------------------------------------------------------
for i=(1:8),
	set(rb_analmotlaw(i),'userdata',rb_analmotlaw(:,[1:(i-1),(i+1):8]))
end

call=[
	'mutex_analmotlaw=get(gcf,''currentobject'');',...
	'if(get(mutex_analmotlaw,''value'')==1),',...
		'set(get(mutex_analmotlaw,''userdata''),''value'',0),',...
	'else,',...
		'set(mutex_analmotlaw,''value'',1),',...
	'end'];
set(rb_analmotlaw,'callback',call);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% setting userdata

set(gcf,'userdata',[ ...
	frame1 ...			
	frame2 ...			
	genmotlaw_tekst ...		
	rb_genmotlaw(1) ...		
	rb_genmotlaw(2) ...		
	rb_genmotlaw(3) ...		
	popup_genmotlaw ...		
	genmotlaw_startangle_tekst ...	
	genmotlaw_startangle_edit ...	
	genmotlaw_startlift_tekst ...	
	genmotlaw_startlift_edit ...	
	genmotlaw_startvel_tekst ...	
	genmotlaw_startvel_edit ...	
	genmotlaw_startacc_tekst ...	
	genmotlaw_startacc_edit ...	
	genmotlaw_startjerk_tekst ...	
	genmotlaw_startjerk_edit ...	
	genmotlaw_endangle_tekst ...	
	genmotlaw_endangle_edit ...	
	genmotlaw_endlift_tekst ...	
	genmotlaw_endlift_edit ...	
	genmotlaw_endvel_tekst ...	
	genmotlaw_endvel_edit ...	
	genmotlaw_endacc_tekst ...	
	genmotlaw_endacc_edit ...	
	genmotlaw_endjerk_tekst ...	
	genmotlaw_endjerk_edit ...	
	genmotlaw_calc ...		
	genmotlaw_add ...		
	genmotlaw_clear	...	
	analmotlaw_tekst ...		
	kin_tekst ...			
	dyn_tekst ...			
	bcr_tekst ...			
	bcr_edit ...			
	rof_tekst ...			
	rof_edit ...			
	exc_tekst ...			
	exc_edit ...			
	mass_tekst ...			
	mass_edit ...			
	spring_tekst ...		
	spring_edit ...			
	sprload_tekst ...			
	sprload_edit ...			
	rpm_tekst ...			
	rpm_edit ...			
	rb_analmotlaw(1) ...		
	rb_analmotlaw(2) ...		
	rb_analmotlaw(3) ...		
	rb_analmotlaw(4) ...		
	rb_analmotlaw(5) ...		
	rb_analmotlaw(6) ...		
	plot_start ...			
	calc_start ...			
	genextload_tekst ...
	genextload_startangle_tekst ...
	genextload_startangle_edit ...
	genextload_startload_tekst ...
	genextload_startload_edit ...%60
	genextload_endangle_tekst ...
	genextload_endangle_edit ...
	genextload_endload_tekst ...
	genextload_endload_edit ...
	genextload_calc ...
	genextload_add ...
   genextload_clear ...
   rb_analmotlaw(7) ...
	rb_analmotlaw(8) ...
   contourgrad_tekst ...
	contourgrad_edit ...
	genmotlaw_save ...
	genmotlaw_load]);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
elseif strcmp(action,'genmotlawload'),

[liftloadfile, liftloadpath]=uigetfile('*.mot','load motion law');

currentliftfile=liftloadfile;
eval(['cd ' liftloadpath]);
eval(['load ' liftloadfile]);
eval(['cd ' rootdir]);

tetatot=[0:1:360];
Stot=eval(strtok(liftloadfile,'.'));

Stotneg2=[Stot(360:361);Stot(1:359)];
Stotneg1=[Stot(361);Stot(1:360)];
Stotpos1=[Stot(2:361);Stot(1)];
Stotpos2=[Stot(3:361);Stot(1:2)];

Vtot=(-Stotpos2+8*Stotpos1-8*Stotneg1+Stotneg2)/12;
Atot=(-Stotpos2+16*Stotpos1-30*Stot+16*Stotneg1-Stotneg2)/12;
Jtot=(Stotpos2-2*Stotpos1+2*Stotneg1-Stotneg2)/2;

		delete(subplot(311))
		delete(subplot(312))
		delete(subplot(313))

		set(axes,'position',[.07 .2 .35 .6]);
		plot(tetatot,Stot),grid on,zoom on,
		title('lift (mm)'),
		xlabel('cam degrees'),
      
     
   genmotlaw_current=uicontrol(gcf,...
		'visible','on',...
		'style','text',...
		'string',currentliftfile,...
		'HorizontalAlignment','left',...
		'foregroundcolor',[.25 .25 1],...
		'backgroundcolor',[.65 .65 .65],...
		'position',[885 480 125 25]+[55 0 -55 0]);
   

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
elseif strcmp(action,'genmotlawsave'),

[liftsavefile, liftsavepath]=uiputfile('*.mot','save motion law');

currentliftfile=liftsavefile;
eval(['cd ' liftsavepath]);
eval(['save ' liftsavefile ' Stot -ascii -double']);
eval(['cd ' rootdir]);

   genmotlaw_current=uicontrol(gcf,...
		'visible','on',...
		'style','text',...
		'string',currentliftfile,...
		'foregroundcolor',[.25 .25 .85],...
		'HorizontalAlignment','left',...
		'backgroundcolor',[.65 .65 .65],...
		'position',[885 480 125 25]+[55 0 -55 0]);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
elseif strcmp(action,'genmotlawcalc'),

ui_handles=get(gcf,'userdata');

rb_genmotlaw(1)=ui_handles(4);
rb_genmotlaw(2)=ui_handles(5);
rb_genmotlaw(3)=ui_handles(6);
popup_genmotlaw=ui_handles(7);
genmotlaw_startangle_edit=ui_handles(9);
genmotlaw_startlift_edit=ui_handles(11);
genmotlaw_startvel_edit=ui_handles(13);
genmotlaw_startacc_edit=ui_handles(15);
genmotlaw_startjerk_edit=ui_handles(17);
genmotlaw_endangle_edit=ui_handles(19);
genmotlaw_endlift_edit=ui_handles(21);
genmotlaw_endvel_edit=ui_handles(23);
genmotlaw_endacc_edit=ui_handles(25);
genmotlaw_endjerk_edit=ui_handles(27);


beta0=str2num(get(genmotlaw_startangle_edit,'string'));
beta1=str2num(get(genmotlaw_endangle_edit,'string'));

L0=str2num(get(genmotlaw_startlift_edit,'string'));
L1=str2num(get(genmotlaw_endlift_edit,'string'));


teta=[beta0:1:beta1];
beta=(beta1-beta0);
x=(teta-beta0)/(beta);

k2=get(popup_genmotlaw,'value');

if get(rb_genmotlaw(1),'value')==1,
	if k2==1
		L=L1-L0;
		S=L*(1-cos(pi*x/2))+L0;
		V=L/beta*pi/2*(sin(pi*x/2));
		A=pi^2*L/beta^2/4*(cos(pi*x/2));
	
	end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
	if k2==2,
		L=L1-L0;
		S=L*(sin(pi*x/2))+L0;
		V=L/beta*pi/2*(cos(pi*x/2));
		A=-pi^2*L/beta^2/4*(sin(pi*x/2));

	end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
	if k2==3,
		L=-(L1-L0);
		S=L*(cos(pi*x/2))+L0-L;
		V=-L/beta*pi/2*(sin(pi*x/2));
		A=-pi^2*L/beta^2/4*(cos(pi*x/2));

	end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
	if k2==4,
		L=-(L1-L0);
		S=L*(1-sin(pi*x/2))+L0-L;
		V=-L/beta*pi/2*(cos(pi*x/2));
		A=pi^2*L/beta^2/4*(sin(pi*x/2));

	end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
	if k2==5,
		L=L1-L0;
		S=L/2*(1-cos(pi*x))+L0;
		V=L/beta*pi/2*(sin(pi*x));
		A=pi^2*L/beta^2/2*(cos(pi*x));

	end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
	if k2==6,
		L=-(L1-L0);
		S=L/2*(1+cos(pi*x))+L0-L;
		V=-L/beta*pi/2*(sin(pi*x));
		A=-pi^2*L/beta^2/2*(cos(pi*x));

	end
end
%-----------------------------------------------------------------------------------
if get(rb_genmotlaw(2),'value')==1,

	if k2==1
		L=L1-L0;
		S=L*(x-sin(pi*x)/pi)+L0;
		V=L/beta*(1-cos(pi*x));
		A=pi*L/beta^2*(sin(pi*x));
	
	end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
	if k2==2,
		L=L1-L0;
		S=L*(x+sin(pi*x)/pi)+L0;
		V=L/beta*(1+cos(pi*x));
		A=-pi*L/beta^2*(sin(pi*x));

	end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
	if k2==3,
		L=-(L1-L0);
		S=L*(1-x+sin(pi*x)/pi)+L0-L;
		V=-L/beta*(1-cos(pi*x));
		A=-pi*L/beta^2*(sin(pi*x));

	end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
	if k2==4,
		L=-(L1-L0);
		S=L*(1-x-sin(pi*x)/pi)+L0-L;
		V=-L/beta*(1+cos(pi*x));
		A=pi*L/beta^2*(sin(pi*x));

	end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
	if k2==5,
		L=L1-L0;
		S=L*(x-sin(2*pi*x)/2/pi)+L0;
		V=L/beta*(1-cos(2*pi*x));
		A=2*pi*L/beta^2*(sin(2*pi*x));

	end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
	if k2==6,
		L=-(L1-L0);
		S=L*(1-x+sin(2*pi*x)/2/pi)+L0-L;
		V=-L/beta*(1-cos(2*pi*x));
		A=-2*pi*L/beta^2*(sin(2*pi*x));

	end
end

%-----------------------------------------------------------------------------------
if get(rb_genmotlaw(3),'value')==1,

	S0=str2num(get(genmotlaw_startlift_edit,'string'));
	V0=str2num(get(genmotlaw_startvel_edit,'string'))*beta;
	A0=str2num(get(genmotlaw_startacc_edit,'string'))*beta^2;
	J0=str2num(get(genmotlaw_startjerk_edit,'string'))*beta^3;
	S1=str2num(get(genmotlaw_endlift_edit,'string'));
	V1=str2num(get(genmotlaw_endvel_edit,'string'))*beta;
	A1=str2num(get(genmotlaw_endacc_edit,'string'))*beta^2;
	J1=str2num(get(genmotlaw_endjerk_edit,'string'))*beta^3;
	Q=[S0 V0 A0 J0 S1 V1 A1 J1]';
	C=[[  1   0   0   0   0   0   0   0];
	   [  0   1   0   0   0   0   0   0];
	   [  0   0   2   0   0   0   0   0];
	   [  0   0   0   6   0   0   0   0];
	   [  1   1   1   1   1   1   1   1];
	   [  0   1   2   3   4   5   6   7];
	   [  0   0   2   6  12  20  30  42];
	   [  0   0   0   6  24  60 120 210]];
	  
	a=(C\Q)';
	S=a*[x.^0 ;x.^1 ;x.^2 ;x.^3 ;x.^4 ;x.^5 ;x.^6 ;x.^7];
	V=a*[0.*x.^0 ;1*x.^0 ;2*x.^1 ;3*x.^2 ;4*x.^3 ;5*x.^4 ;6*x.^5 ;7*x.^6]/beta;
	A=a*[0.*x.^0 ;0.*x.^0 ;1*2*x.^0 ;2*3*x.^1 ;3*4*x.^2 ;4*5*x.^3 ;5*6*x.^4 ;6*7*x.^5]/beta^2;

end
	subplot(311)
	set(subplot(311),'position',[.07 .75 .35 .2])
	plot(teta,S),grid on,zoom on
	title('heffing (mm)')

	subplot(312)
	set(subplot(312),'position',[.07 .425 .35 .2])
	plot(teta,V),grid on,zoom on
	title('snelheid (mm / graad)')

	subplot(313)
	set(subplot(313),'position',[.07 .1 .35 .2])
	plot(teta,A),grid on,zoom on
	title('versnelling (mm / graad^2)')
	xlabel('nokgraden')


elseif strcmp(action,'genmotlawadd'),

	Stot(beta0+1:1:beta1+1)=S;
	Vtot(beta0+1:1:beta1+1)=V;
	Atot(beta0+1:1:beta1+1)=A;
	tetatot=[0:1:360];
	tetatotrad=tetatot*pi/180;

	subplot(311)
	set(subplot(311),'position',[.07 .75 .35 .2])
	plot(tetatot,Stot),grid on,zoom on
	title('heffing (mm)')

	subplot(312)
	set(subplot(312),'position',[.07 .425 .35 .2])
	plot(tetatot,Vtot),grid on,zoom on
	title('snelheid (mm / graad)')

	subplot(313)
	set(subplot(313),'position',[.07 .1 .35 .2])
	plot(tetatot,Atot),grid on,zoom on
	title('versnelling (mm / graad^2)')
	xlabel('nokgraden')

elseif strcmp(action,'genmotlawclear'),

	Stot=zeros(361,1);
	Vtot=zeros(361,1);
	Atot=zeros(361,1);
	tetatot=[0:1:360];

	subplot(311)
	set(subplot(311),'position',[.07 .75 .35 .2])
	plot(tetatot,Stot),grid on,zoom on
	title('lift (mm)')

	subplot(312)
	set(subplot(312),'position',[.07 .425 .35 .2])
	plot(tetatot,Vtot),grid on,zoom on
	title('velocity (mm / cam degree)')

	subplot(313)
	set(subplot(313),'position',[.07 .1 .35 .2])
	plot(tetatot,Atot),grid on,zoom on
	title('acceleration (mm / cam degree^2)')
	xlabel('cam degrees')
   
   currentfile='newfile';
   genmotlaw_current=uicontrol(gcf,...
		'visible','on',...
		'style','text',...
		'string',currentfile,...
		'HorizontalAlignment','left',...
		'foregroundcolor',[.85 .25 .25],...
		'backgroundcolor',[.65 .65 .65],...
		'position',[885 480 125 25]+[55 0 -55 0]);

elseif strcmp(action,'calc')
	
	ui_handles=get(gcf,'userdata');
	bcr_edit=ui_handles(35);
	rof_edit=ui_handles(37);
	exc_edit=ui_handles(39);
	mass_edit=ui_handles(41);
	spring_edit=ui_handles(43);
	sprload_edit=ui_handles(45);
	rpm_edit=ui_handles(47);
   contourgrad_edit=ui_handles(71);
   
	bcr=str2num(get(bcr_edit,'string'));
	rof=str2num(get(rof_edit,'string'));
	exc=str2num(get(exc_edit,'string'));
	mass=str2num(get(mass_edit,'string'));
	spring=str2num(get(spring_edit,'string'));
	sprload=str2num(get(sprload_edit,'string'));
	rpm=str2num(get(rpm_edit,'string'));
   grad_contourplot=str2num(get(contourgrad_edit,'string'));

	Stotrad=Stot;
	Vtotrad=Vtot*180/pi;
	Atotrad=Atot*(180/pi)^2;
	alfa=atan((Vtotrad-exc)./(sqrt((bcr+rof)^2-exc^2)+Stotrad))*180/pi;

   % berekening van de contour
   x_c_0=exc;
   y_c_0=sqrt((bcr+rof).^2-(exc).^2);
   x_c=x_c_0+0;
   y_c=y_c_0+Stotrad;
   lambda=atan(x_c./y_c)';

   Rtotrad=sqrt(x_c.^2+y_c.^2);
   
   x_pitch=Rtotrad.*sin(tetatot*pi/180+lambda)';
   y_pitch=Rtotrad.*cos(tetatot*pi/180+lambda)';
   x_contour=x_pitch-rof.*sin((tetatot'-alfa)*pi/180);
   y_contour=y_pitch-rof.*cos((tetatot'-alfa)*pi/180);   
   
   x_pitch_plot=x_pitch.*cos(grad_contourplot*pi/180)-y_pitch.*sin(grad_contourplot*pi/180);
   y_pitch_plot=x_pitch.*sin(grad_contourplot*pi/180)+y_pitch.*cos(grad_contourplot*pi/180);
   x_contour_plot=x_contour.*cos(grad_contourplot*pi/180)-y_contour.*sin(grad_contourplot*pi/180);
   y_contour_plot=x_contour.*sin(grad_contourplot*pi/180)+y_contour.*cos(grad_contourplot*pi/180);
   
   x_rolfol=rof*cos([0:1:360]/180*pi)+exc;
   y_rolfol=rof*sin([0:1:360]/180*pi)+sqrt((rof+bcr)^2-exc^2)+Stotrad(grad_contourplot+1);
   x_rod_ref=[exc exc];
   y_rod_ref=[sqrt((rof+bcr)^2-exc^2) sqrt((rof+bcr)^2-exc^2)+rof*4+max(Stot)];
   x_rod=x_rod_ref;
   y_rod=y_rod_ref+Stotrad(grad_contourplot+1);
   x_boreleft=[exc-5 exc-1 exc-1 exc-5];
   x_boreright=[exc+5 exc+1 exc+1 exc+5];
   y_bore=[2*rof 2*rof 4*rof 4*rof]+max(Stot)+sqrt((rof+bcr)^2-exc^2);
   
   x_refangle=[0 bcr*sin(-grad_contourplot*pi/180)];
   y_refangle=[0 bcr*cos(-grad_contourplot*pi/180)];

   
   x_pressangle=[x_rod(1)+rof*sin(alfa(grad_contourplot+1)*pi/180) x_rod(1)-2*rof*sin(alfa(grad_contourplot+1)*pi/180)];
   y_pressangle=[y_rod(1)-rof*cos(alfa(grad_contourplot+1)*pi/180) y_rod(1)+2*rof*cos(alfa(grad_contourplot+1)*pi/180)];
   x_center=[0,exc];
   y_center=[0,sqrt((rof+bcr)^2-exc^2)+Stotrad(grad_contourplot+1)];
   
   % berekening van de afgeleiden
   RRtotrad=interp1([tetatot+lambda*180/pi],Rtotrad,tetatot,'spline')';
   
   RRtotrad_2=[RRtotrad(360:361);RRtotrad(1:359)];
	RRtotrad_1=[RRtotrad(361);RRtotrad(1:360)];
	RRtotrad0=RRtotrad(1:361);
	RRtotrad1=[RRtotrad(2:361);RRtotrad(1)];
	RRtotrad2=[RRtotrad(3:361);RRtotrad(1:2)];

	RVtotrad=(-RRtotrad2+8*RRtotrad1-8*RRtotrad_1+RRtotrad_2)/12*180/pi;
	RAtotrad=(-RRtotrad2+16*RRtotrad1-30*RRtotrad0+16*RRtotrad_1-RRtotrad_2)/12*(180/pi)^2;

	
	roc=((RRtotrad.^2+RVtotrad.^2).^1.5)./(RRtotrad.^2+2*RVtotrad.^2-RRtotrad.*RAtotrad)-rof;
   
   roc=interp1(tetatot,roc,[tetatot+lambda*180/pi],'spline');
	roc_plot=roc;
   
   force_spring=(Stot*spring+sprload)./cos(alfa/180*pi);
	force_load=extloadtot./cos(alfa/180*pi);
	force_acc=Atot*((rpm*360/60)^2)./cos(alfa/180*pi)/1000*mass;
   force_tot=force_spring+force_load+force_acc;
   force_x=force_tot.*cos(alfa/180*pi);
   force_y=force_tot.*sin(alfa/180*pi);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

elseif strcmp(action,'plot'),
	ui_handles=get(gcf,'userdata');
	rb_analmotlaw(1)=ui_handles(48);
	rb_analmotlaw(2)=ui_handles(49);
	rb_analmotlaw(3)=ui_handles(50);
	rb_analmotlaw(4)=ui_handles(51);
	rb_analmotlaw(5)=ui_handles(52);
   rb_analmotlaw(6)=ui_handles(53);
   rb_analmotlaw(7)=ui_handles(68);
   rb_analmotlaw(8)=ui_handles(69);



	delete(subplot(311))
	delete(subplot(312))
	delete(subplot(313))

   if get(rb_analmotlaw(1),'value')==1,
      
		set(axes,'position',[.07 .2 .35 .6]);
		plot(tetatot,Stot),grid on,zoom on,
		title('lift (mm)'),
		xlabel('cam degrees'),
		
	end

   if get(rb_analmotlaw(2),'value')==1,
      
		set(axes,'position',[.07 .2 .35 .6]);
		plot(tetatot,Vtot),grid on,zoom on,
		title('velocity (mm / cam degree)'),
		xlabel('cam degrees'),
		
	end

   if get(rb_analmotlaw(3),'value')==1,
      
		set(axes,'position',[.07 .2 .35 .6]);
		plot(tetatot,Atot),grid on,zoom on,
		title('acceleration (mm / cam degree^2)'),
		xlabel('cam degrees'),
		
	end

   if get(rb_analmotlaw(4),'value')==1,
      
		set(axes,'position',[.07 .2 .35 .6]);
		plot(tetatot,alfa),grid on,zoom on,
		title('pressure angle (degrees)'),
		xlabel('cam degrees'),
		
	end

   if get(rb_analmotlaw(5),'value')==1,
      
		set(axes,'position',[.07 .2 .35 .6]);
		axis([0 400 -500 500]),hold on
		plot(tetatot,roc),grid on,zoom on,hold off
		title('curvature radius (mm)'),
	end

   if get(rb_analmotlaw(6),'value')==1,
      
      set(axes,'position',[.07 .2 .35 .6]);
		plot(tetatot,force_spring,'m:',tetatot,force_load,'r-.',tetatot,force_acc,'g--',tetatot,force_tot,'b-'),grid on,zoom on,hold off
      title('contact force (N)'),
      xlabel('cam degrees'),
      ylimits=get(gca,'Ylim');
      ylim=ylimits(2)-ylimits(1);
      y_legend(1)=ylimits(2)-ylim*.1;
		y_legend(2)=ylimits(2)-ylim*.15;
      y_legend(3)=ylimits(2)-ylim*.2;
      y_legend(4)=ylimits(2)-ylim*.25;
      xlimits=get(gca,'Xlim');
      xlim=xlimits(2)-xlimits(1);
      x_legend=xlimits(1)+.7*xlim;
            
      set(text(x_legend,y_legend(1),'total load (-)'),'color',[0 0 1]);
		set(text(x_legend,y_legend(2),'inertia load (--)'),'color',[0 1 0]);
		set(text(x_legend,y_legend(3),'spring load (..)'),'color',[1 0 1]);
		set(text(x_legend,y_legend(4),'external load (-.)'),'color',[1 0 0]);

	

	end
   
   if get(rb_analmotlaw(8),'value')==1,
      
      set(axes,'position',[.07 .2 .35 .6]);
		plot(tetatot,force_x,'b-',tetatot,force_y,'r-.'),grid on,zoom on,hold off
      title('reaction forces (N)'),
      xlabel('cam degrees'),
      ylimits=get(gca,'Ylim');
      ylim=ylimits(2)-ylimits(1);
      y_legend(1)=ylimits(2)-ylim*.1;
		y_legend(2)=ylimits(2)-ylim*.15;
      xlimits=get(gca,'Xlim');
      xlim=xlimits(2)-xlimits(1);
      x_legend=xlimits(1)+.65*xlim;
            
      set(text(x_legend,y_legend(1),'X-reaction force (-)'),'color',[0 0 1]);
		set(text(x_legend,y_legend(2),'Y-reaction force (-.)'),'color',[1 0 0]);	

	end
   

   if get(rb_analmotlaw(7),'value')==1,
      
		set(axes,'position',[.07 .2 .35 .6]);
      axis([-max(Rtotrad), max(Rtotrad), -max(Rtotrad), max(Rtotrad)+6*rof]);
      axis manual
      fill([-rof/2 rof/2 rof/2 -rof/2]+x_rod(2),[0 0 rof/2 rof/2]+y_rod(2),'g'),hold on,
%      plot([-rof/2 rof/2]+x_rod_ref(2),[0 0]+y_rod_ref(2),'k'),hold on,
      fill(x_rolfol,y_rolfol,'g'),
      fill(x_contour_plot,y_contour_plot,'b'),
      plot(x_pitch_plot,y_pitch_plot,'r-.'),
      plot(x_center,y_center,'r+'),
      plot(x_pressangle,y_pressangle,'r--'),
      plot(x_refangle,y_refangle,'r--'),
      plot(x_boreleft,y_bore,'r'),
      plot(x_boreright,y_bore,'r'),
      %plot(x_rod_ref(2),y_rod_ref(2),'bv'),
      %plot(x_rod(2),y_rod(2),'b^'),
      plot([x_rod(1) x_rod_ref(2)],[y_rod(1) y_rod_ref(2)],'r'),
      plot([x_rod_ref(2) x_rod(2)],[y_rod_ref(2) y_rod(2)],'b'),grid on,zoom on,axis('equal'),hold off
      title('cam contour (mm)'),
      ylimits=get(gca,'Ylim');
      ylim=ylimits(2)-ylimits(1);
      y_legend(1)=ylimits(1)+ylim*.1;
      y_legend(2)=ylimits(1)+ylim*.05;
      xlimits=get(gca,'Xlim');
      xlim=xlimits(2)-xlimits(1);
      x_legend=xlimits(1)+.65*xlim;
            
      set(text(x_legend,y_legend(2),'pitch curve (-.)'),'color',[1 0 0]);
		set(text(x_legend,y_legend(1),'cam curve'),'color',[0 0 1]);
		set(text(x_rod(2)+10,(y_rod_ref(2)+y_rod(2))/2,'lift'),'color',[0 0 1]);
      axis([-max(Rtotrad), max(Rtotrad), -max(Rtotrad), max(Rtotrad)+6*rof]);

	end


elseif strcmp(action,'genextloadcalc'),

ui_handles=get(gcf,'userdata');

genextload_startangle_edit=ui_handles(58);
genextload_startlift_edit=ui_handles(60);
genextload_endangle_edit=ui_handles(62);
genextload_endlift_edit=ui_handles(64);

betaload0=str2num(get(genextload_startangle_edit,'string'));
betaload1=str2num(get(genextload_endangle_edit,'string'));

Load0=str2num(get(genextload_startlift_edit,'string'));
Load1=str2num(get(genextload_endlift_edit,'string'));

extload=0;
for i=(1:1:betaload1-betaload0+1)
   extload(i)=Load0+(Load1-Load0)/(betaload1-betaload0)*(i-1);
end   
betaload=[betaload0:1:betaload1];

	delete(subplot(311))
	delete(subplot(312))
	delete(subplot(313))

axis off
set(axes,'position',[.07 .2 .35 .6]);
plot(betaload,extload),grid on,zoom on,axis on
title('external load (N)')
xlabel('cam degrees')


elseif strcmp(action,'genextloadadd'),

	extloadtot(betaload0+1:1:betaload1+1)=extload;
   betaloadtot=[0:1:360];
   
  	delete(subplot(311))
	delete(subplot(312))
	delete(subplot(313))

   axis off
	set(axes,'position',[.07 .2 .35 .6]);
	plot(betaloadtot,extloadtot),grid on,zoom on,axis on
	title('external load (N)')
	xlabel('cam degrees')

elseif strcmp(action,'genextloadclear'),

   extloadtot=zeros(361,1);
   betaloadtot=[0:1:360];
   
   currentloadfile='newfile';
   
  	delete(subplot(311))
	delete(subplot(312))
	delete(subplot(313))

   axis off
	set(axes,'position',[.07 .2 .35 .6]);
	plot(betaloadtot,extloadtot),grid on,zoom on,axis on
	title('external load (N)')
	xlabel('cam degrees')
   
      genmotlaw_current=uicontrol(gcf,...
		'visible','on',...
		'style','text',...
		'string',currentloadfile,...
		'HorizontalAlignment','left',...
		'foregroundcolor',[.85 .25 .25],...
		'backgroundcolor',[.65 .65 .65],...
		'position',[885 65 125 25]+[55 0 -55 0]);


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
elseif strcmp(action,'genextloadload'),
[loadloadfile, loadloadpath]=uigetfile('*.exl','load external load file');


currentloadfile=loadloadfile;
eval(['cd ' loadloadpath]);
eval(['load ' loadloadfile]);
eval(['cd ' rootdir]);

betaloadtot=[0:1:360];
extloadtot=eval(strtok(loadloadfile,'.'));

		delete(subplot(311))
		delete(subplot(312))
		delete(subplot(313))

   axis off
	set(axes,'position',[.07 .2 .35 .6]);
	plot(betaloadtot,extloadtot),grid on,zoom on,axis on
	title('external load (N)')
	xlabel('cam degrees')
      
     
   genmotlaw_current=uicontrol(gcf,...
		'visible','on',...
		'style','text',...
		'string',currentloadfile,...
		'HorizontalAlignment','left',...
		'foregroundcolor',[.25 .25 1],...
		'backgroundcolor',[.65 .65 .65],...
		'position',[885 65 125 25]+[55 0 -55 0]);
   

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
elseif strcmp(action,'genextloadsave'),

[loadsavefile, loadsavepath]=uiputfile('*.exl','save external load file');
   
currentloadfile=loadsavefile;
eval(['cd ' loadsavepath]);
eval(['save ' loadsavefile ' extloadtot -ascii -double']);
eval(['cd ' rootdir]);

   genmotlaw_current=uicontrol(gcf,...
		'visible','on',...
		'style','text',...
		'string',currentloadfile,...
		'foregroundcolor',[.25 .25 .85],...
		'HorizontalAlignment','left',...
		'backgroundcolor',[.65 .65 .65],...
		'position',[885 65 125 25]+[55 0 -55 0]);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
end